---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: terminal
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: terminal
  template:
    metadata:
      labels:
        app.kubernetes.io/name: terminal
    spec:
      serviceAccountName: {{ .Values.terminal.serviceAccount }}
      containers:
      - name: terminal
        image: {{ .Values.terminal.image }}
        imagePullPolicy: Always
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
         - containerPort: 8080
           protocol: TCP
        resources:
          {{- toYaml .Values.terminal.resources | nindent 10 }}
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            drop: ["ALL"]
      securityContext:
        runAsNonRoot: false
        seccompProfile:
          type: RuntimeDefault