---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.terminal.serviceAccount }}
  namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin-{{ .Values.terminal.serviceAccount }}
  labels:
    app.kubernetes.io/instance: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: {{ .Values.terminal.serviceAccount }}
  namespace: {{ .Values.namespace }}
