---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: documentation
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: documentation
  template:
    metadata:
      labels:
        app.kubernetes.io/name: documentation
    spec:
      containers:
      - name: documentation
        image: image-registry.openshift-image-registry.svc:5000/{{ .Values.namespace }}/documentation:latest
        imagePullPolicy: Always
        ports:
         - containerPort: 8080
           protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
        resources:
          {{- toYaml .Values.documentation.resources | nindent 10 }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
