---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: documentation
  namespace: {{ .Values.namespace }}
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: documentation
  namespace: {{ .Values.namespace }}
spec:
  output:
    to:
      kind: ImageStreamTag
      name: documentation:latest
  source:
    binary: {}
    type: Binary
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: httpd:2.4
        namespace: openshift
    type: Source
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: showroom
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: antora
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    description: |
      Build Antora site.
spec:
  workspaces:
  - name: source
    mountPath: /antora
  steps:
  - name: build
    # image: docker.io/antora/antora:latest
    image: quay.io/openshiftlabs/antora-for-mad-ws:1.0
    args:
    - site.yml
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: showroom
  namespace: {{ .Values.namespace }}
spec:
  resourcetemplates:
  - apiVersion: tekton.dev/v1
    kind: PipelineRun
    metadata:
      generateName: showroom-
    spec:
      pipelineRef:
        name: showroom
      workspaces:
      - name: showroom
        persistentVolumeClaim:
          claimName: showroom
---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: showroom
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  workspaces:
  - name: showroom
  tasks:
  - name: git-clone
    taskRef:
      kind: ClusterTask
      name: git-clone
    params:
    - name: url
      value: {{ .Values.documentation.repoUrl }}
    - name: revision
      value: {{ .Values.documentation.repoRevision }}
    - name: deleteExisting
      value: 'true'
    workspaces:
    - name: output
      workspace: showroom
  - name: build-antora
    runAfter:
    - git-clone
    taskRef:
      kind: Task
      name: antora
    workspaces:
    - name: source
      workspace: showroom
  - name: build-image
    runAfter:
    - build-antora
    taskRef:
      kind: ClusterTask
      name: openshift-client
    params:
    - name: SCRIPT
      value: |
        oc start-build documentation --from-dir="gh-pages" -n {{ .Values.namespace }} --wait=true
    workspaces:
    - name: manifest-dir
      workspace: showroom
---
apiVersion: batch/v1
kind: Job
metadata:
  name: showroom-pipeline-run
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  backoffLimit: 3
  template:
    spec:
      serviceAccountName: pipeline
      restartPolicy: Never
      containers:
      - name: main
        image: registry.redhat.io/openshift-pipelines/pipelines-cli-tkn-rhel8:v1.11.0-25
        command:
        - /bin/bash
        - -c
        - |
          tkn pipeline start showroom --workspace name=showroom,claimName=showroom --use-param-defaults -n {{ .Values.namespace }}
