{{- if not .Values.documentation.url }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: documentation
  namespace: {{ .Values.namespace }}
spec:
  to:
    kind: Service
    name: documentation
  port:
    targetPort: 8080
  tls:
    termination: edge
  wildcardPolicy: None
{{- end }}
