{{- if not .Values.documentation.url }}
---
apiVersion: v1
kind: Service
metadata:
  name: documentation
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: documentation
{{- end }}
