# Default values for showroom.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: showroom

deployer:
  domain: apps.cluster-guid.sandbox.opentlc.com

home:
  image: registry.redhat.io/ubi8/httpd-24:latest
  contentMount: /var/www/html/
  contentConfig: showroom-html
  resources:
    limits:
      memory: 64Mi
    requests:
      cpu: 100m
      memory: 64Mi

documentation:
  repoUrl: https://github.com/tonykay/showroom-poc-2023-06.git
  repoRevision: development
  antora:
    image: quay.io/openshiftlabs/antora-for-mad-ws:1.0
    # Image: docker.io/antora/antora:latest
  resources:
    limits:
      memory: 64Mi
    requests:
      cpu: 100m
      memory: 64Mi

terminal:
  image: ghcr.io/juliaaano/terminal:latest
  name: terminal
  serviceAccount: showroom
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 500m
      memory: 256Mi

codeserver:
  url: http://codeserver:8080
  image: docker.io/codercom/code-server:latest
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 512Mi
